---
# Версия платформы 1С
platform_version: "8.3.26.1521"

# Пути установки
one_c_install_path: "C:\\Program Files\\1cv8\\{{ platform_version }}"
one_c_platform_path: "{{ one_c_install_path }}"

# Параметры 1С
cluster_name: "base1"

# Префикс для портов (первые две цифры)
port_prefix: "15"

# Порты для сервисов 1С
ragent_port: "{{ port_prefix }}40"
rmngr_port: "{{ port_prefix }}41"
rphost_start_port: "{{ port_prefix }}60"
rphost_end_port: "{{ port_prefix }}91"
ras_port: "{{ port_prefix }}45"

# Управление платформой
remove_old_platform: false  # Удалять ли предыдущую версию платформы
platform_version_to_remove: ""  # Версия платформы, которую нужно удалить (пусто - удалить все кроме новой)

# Параметры службы Windows
service_name: "1CEnterprise{{ platform_version | regex_replace('\\.', '') }}Server"
service_display_name: "1C:Enterprise {{ platform_version }} Server"
service_description: "1C:Enterprise {{ platform_version }} Server Service"
service_user: "LocalSystem" 