---
- name: Установка Postgres Pro 1C
  hosts: postgres_hosts
  become: yes
  roles:
    - postgres

- name: Установка платформы 1С
  hosts: one_c_hosts
  become: yes
  roles:
    - one_c_server

- name: Создание базы данных 1С
  hosts: postgres_hosts
  become: yes
  roles:
    - one_c_database 

- name: Установка лицензирования 1С
  hosts: one_c_license_servers
  become: yes
  roles:
    - one_c_license_server