---
- name: Установка Postgres Pro 1C
  hosts: postgres_hosts
  become: yes
  roles:
    - postgres

- name: Установка платформы 1С
  hosts: one_c_hosts
  become: yes
  roles:
    - one_c_server

- name: Создание базы данных 1С
  hosts: postgres_hosts
  become: yes
  roles:
    - one_c_database
  when: create_database | default(false) | bool 