---
# Версия платформы 1С
platform_version: "8.3.26.1521" 

# Параметры 1С
1c_group: "grp1cv8"
1c_user: "usr1cv8"
1c_home: "/home/usr1cv8"
one_c_platform_path: "/opt/1cv8/x86_64/{{ platform_version }}"

# Управление платформой
remove_old_platform: false  # Удалять ли предыдущую версию платформы
platform_version_to_remove: ""  # Версия платформы, которую нужно удалить (пусто - удалить все кроме новой)

# Название кластера
cluster_name: "base1"

# Префикс для портов (первые две цифры)
port_prefix: "15"

# Порты для сервисов 1С
ragent_port: "{{ port_prefix }}40"
rmngr_port: "{{ port_prefix }}41"
rphost_start_port: "{{ port_prefix }}60"
rphost_end_port: "{{ port_prefix }}91"
ras_port: "{{ port_prefix }}45" 