---
# defaults file for roles/one_c_license_server

# Путь к платформе 1С
one_c_platform_path: "/opt/1cv8/x86_64/{{ platform_version }}"

# Настройки кластера
cluster_name: "lic"

# Префикс для портов (первые две цифры)
port_prefix: "15"

# Порты для сервисов 1С
ragent_port: "{{ port_prefix }}40"
rmngr_port: "{{ port_prefix }}41"
rphost_start_port: "{{ port_prefix }}60"
rphost_end_port: "{{ port_prefix }}91"
ras_port: "{{ port_prefix }}45" 

