---
# tasks file for roles/one_c_license_server

- name: Установка необходимых пакетов
  apt:
    name:
      - wget
      - libsm6
      - libwebkit2gtk-4.0-37
      - openjdk-11-jdk
    state: present
    update_cache: yes

- name: Установка платформы 1С
  block:
    - name: Копирование пакетов 1С
      copy:
        src: "{{ role_path }}/files/1c-enterprise-{{ platform_version }}-{{ item }}_{{ platform_version | regex_replace('\\.(?=[^.]*$)', '-') }}_amd64.deb"
        dest: "/tmp/1c-enterprise-{{ platform_version }}-{{ item }}_{{ platform_version | regex_replace('\\.(?=[^.]*$)', '-') }}_amd64.deb"
      loop:
        - common
        - server
        - ws

    - name: Установка пакетов 1С
      apt:
        deb: "{{ '/tmp/1c-enterprise-' + platform_version + '-' + item + '_' + (platform_version | regex_replace('\\.(?=[^.]*$)', '-')) + '_amd64.deb' }}"
        state: present
      loop:
        - common
        - server
        - ws

- name: Установка инструментов лицензирования 1С
  block:
    - name: Копирование архива инструментов лицензирования
      copy:
        src: "{{ role_path }}/files/1c_enterprise_license_tools_0.15.0_2_linux_x86_64.tar.gz"
        dest: "/tmp/1c_enterprise_license_tools_0.15.0_2_linux_x86_64.tar.gz"

    - name: Распаковка архива инструментов лицензирования
      unarchive:
        src: "/tmp/1c_enterprise_license_tools_0.15.0_2_linux_x86_64.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Установка инструментов лицензирования
      command: "./1ce-installer-cli install --ignore-signature-warnings"
      args:
        chdir: "/tmp"
        creates: "/usr/bin/1ce-installer-cli"

- name: Настройка службы RAS
  block:
    - name: Копирование службы RAS
      copy:
        src: "{{ one_c_platform_path }}/ras-{{ platform_version }}.service"
        dest: "{{ one_c_platform_path }}/ras-{{ platform_version }}@.service"
        remote_src: yes
        mode: '0644'

    - name: Изменение описания службы RAS
      replace:
        path: "{{ one_c_platform_path }}/ras-{{ platform_version }}@.service"
        regexp: 'Description=1C:Enterprise Remote Administration Server 8.3 \({{ platform_version }}\)'
        replace: 'Description=1C:Enterprise Remote Administration Server 8.3 ({{ platform_version }}) (%I)'

    - name: Линковка RAS
      command: systemctl link {{ one_c_platform_path }}/ras-{{ platform_version }}@.service
      args:
        creates: /etc/systemd/system/ras-{{ platform_version }}@.service

    - name: Создание директории для конфигурации службы RAS
      file:
        path: /etc/systemd/system/ras-{{ platform_version }}@{{ cluster_name }}_{{ ragent_port }}.service.d
        state: directory
        mode: '0755'

    - name: Создание конфигурации службы RAS
      template:
        src: ras.override.conf.j2
        dest: /etc/systemd/system/ras-{{ platform_version }}@{{ cluster_name }}_{{ ragent_port }}.service.d/override.conf
        mode: '0644'

- name: Линковка служб 1С
  block:
    - name: Линковка сервера 1С
      command: systemctl link {{ one_c_platform_path }}/srv1cv8-{{ platform_version }}@.service
      args:
        creates: /etc/systemd/system/srv1cv8-{{ platform_version }}@.service

    - name: Создание директории для конфигурации службы 1С
      file:
        path: /etc/systemd/system/srv1cv8-{{ platform_version }}@{{ cluster_name }}_{{ ragent_port }}.service.d
        state: directory
        mode: '0755'

- name: Настройка службы 1С
  block:
    - name: Создание конфигурации службы 1С
      template:
        src: srv1cv8.override.conf.j2
        dest: /etc/systemd/system/srv1cv8-{{ platform_version }}@{{ cluster_name }}_{{ ragent_port }}.service.d/override.conf
        mode: '0644'

    - name: Перезагрузка systemd
      systemd:
        daemon_reload: yes

    - name: Включение и запуск службы 1С
      systemd:
        name: srv1cv8-{{ platform_version }}@{{ cluster_name }}_{{ ragent_port }}
        state: started
        enabled: yes

    - name: Включение и запуск службы RAS
      systemd:
        name: ras-{{ platform_version }}@{{ cluster_name }}_{{ ragent_port }}
        state: started
        enabled: yes

