---
- name: Установка необходимых пакетов
  apt:
    name:
      - wget
      - gnupg2
      - lsb-release
    state: present
    update_cache: yes

- name: Установка Postgres Pro 1C
  block:
    - name: Проверка существования репозитория
      stat:
        path: /etc/apt/sources.list.d/postgresql-1c-{{ postgres_version }}.list
      register: repo_file

    - name: Удаление существующего репозитория
      file:
        path: /etc/apt/sources.list.d/postgresql-1c-{{ postgres_version }}.list
        state: absent
      when: repo_file.stat.exists

    - name: Скачивание скрипта репозитория
      get_url:
        url: https://repo.postgrespro.ru/1c/1c-{{ postgres_version }}/keys/pgpro-repo-add.sh
        dest: /tmp/pgpro-repo-add.sh
        mode: '0755'

    - name: Выполнение скрипта репозитория
      command: sh /tmp/pgpro-repo-add.sh
      args:
        creates: /etc/apt/sources.list.d/pgpro-1c.list

    - name: Установка Postgres Pro 1C
      apt:
        name: postgrespro-1c-{{ postgres_version }}
        state: present

    - name: Копирование службы Postgres Pro 1C
      copy:
        src: /lib/systemd/system/postgrespro-1c-{{ postgres_version }}.service
        dest: /lib/systemd/system/postgrespro-1c-{{ postgres_version }}@.service
        remote_src: yes
        mode: '0644'

    - name: Изменение описания службы Postgres Pro 1C
      replace:
        path: /lib/systemd/system/postgrespro-1c-{{ postgres_version }}@.service
        regexp: 'Description=Postgres Pro 1c {{ postgres_version }} database server'
        replace: 'Description=Postgres Pro 1c {{ postgres_version }} database server (%i)'

    - name: Вывод информации о переменных окружения сервиса
      ansible.builtin.debug:
        var: service_env.stdout_lines

    - name: Изменение пользователя и группы в службе
      replace:
        path: /lib/systemd/system/postgrespro-1c-{{ postgres_version }}@.service
        regexp: 'User=postgres\nGroup=postgres'
        replace: 'User={{ postgres_user }}\nGroup={{ postgres_group }}'

    - name: Перезагрузка systemd
      systemd:
        daemon_reload: yes

    - name: Создание директории для данных PostgreSQL
      file:
        path: /var/lib/pgpro/1c-{{ postgres_version }}/{{ postgres_port }}
        state: directory
        owner: "{{ postgres_user }}"
        group: "{{ postgres_group }}"
        mode: '0700'

    - name: Проверка существования директории базы данных
      ansible.builtin.stat:
        path: /var/lib/pgpro/1c-{{ postgres_version }}/{{ postgres_port }}/PG_VERSION
      register: _initdb_signal

    - name: Инициализация базы данных PostgreSQL через su
      ansible.builtin.shell: |
        su - {{ postgres_user }} -c "/opt/pgpro/1c-{{ postgres_version }}/bin/initdb \
          --pgdata=/var/lib/pgpro/1c-{{ postgres_version }}/{{ postgres_port }} \
          --locale=ru_RU.UTF-8 \
          --no-sync \
          --encoding=UTF8 \
          --auth=trust \
          --set port={{ postgres_port }}"
      register: _initdb_exec
      when: not _initdb_signal.stat.exists

    - name: Создание файла конфигурации кластера
      template:
        src: postgres.cluster.conf.j2
        dest: /etc/default/postgrespro-1c-{{ postgres_version }}-{{ postgres_port }}
        mode: '0644'

    - name: Создание директории для конфигурации службы Postgres Pro 1C
      file:
        path: /etc/systemd/system/postgrespro-1c-{{ postgres_version }}@{{ cluster_name }}_{{ postgres_port }}.service.d
        state: directory
        mode: '0755'

    - name: Создание конфигурации службы Postgres Pro 1C
      template:
        src: postgres.override.conf.j2
        dest: /etc/systemd/system/postgrespro-1c-{{ postgres_version }}@{{ cluster_name }}_{{ postgres_port }}.service.d/override.conf
        mode: '0644'

    - name: Включение и запуск Postgres Pro 1C
      systemd:
        name: postgrespro-1c-{{ postgres_version }}@{{ cluster_name }}_{{ postgres_port }}
        state: started
        enabled: yes

    - name: Проверка состояния сервиса Postgres Pro 1C
      ansible.builtin.shell: >
        systemctl show postgrespro-1c-{{ postgres_version }}@{{ cluster_name }}_{{ postgres_port }} | grep -E 'Environment|ExecStart'
      register: service_env
      changed_when: false